### ISSUE TITLE
Getting CSRF token verification failed! with CAPROVER after Enabling Https

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [caprover/one-click-apps#590]
Used Zammad version: 5.0.1-5
Used Zammad installation type: (source, package, docker-compose, …) - Caprover
Operating system: ubuntu 18.04
Browser + version: Version 96.0.4664.110 (Official Build) (64-bit)

**Expected behavior:**
I was able to login to the Zammad portal until I unable force https
Caprover was showing user default user name and password for zammad login
![image](https://user-images.githubusercontent.com/36895131/147392389-a9090c92-b3a3-4a50-9cbb-5031933b070a.png)

**Actual behavior:**
I am not able to login to the Zammad portal after I unable force https

Caprover not showing default user name and password for zammad login
image

install Zammad through caprover
enable https

**Comment by githubsaturn** [comment]
CapRover apps are community maintained. You can report issues with installation on the PR that introduced an app. 

Here is the pull request that introduced Zommad: https://github.com/caprover/one-click-apps/pull/535

**Comment by belcboo** [comment]
I had this same issue and after trying a lot of stuff I solved by doing the following changes, in the service: 

zammad-nginx

you need to add the two following ENVs:

VIRTUAL_HOST: your-fqdn.
NGINX_SERVER_SCHEME: https

After that the CSRF token error disappeared.

Im gonna make the mods to the One Click Up to request this two ENVs on creation of the App.

**Comment by joshlopes** [comment]
I confirm that this is still an issue and that @belcboo is a life savior -- I would be here for ages if you wasn't by your comment. Looking back at the initial PR it feels like the "scheme" is being scaped or something? Anyway adding these TWO vars does fix the issue -- so probably worth to change the one-click-app to add it and make it more obvious.

**Comment by joshlopes** [comment]
@githubsaturn can you reopen this issue so we can keep track? As it stands the one click app is amazing -- but this thing is a feature-kill since people will think it won't work after successfully setting it up.

**Comment by githubsaturn** [comment]
@joshlopes - one click apps are community maintained. Fee free to open a PR to fix.
